### ISSUE TITLE
after new install

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#15]
I had some database errors so I did a complete fresh install. Till adding a new game, all went well. But after adding a new game, I got this error:

![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26418402/62624f92-40bc-11e7-9368-ba8f4fa81e49.png)
It seems its looking for a log file, but can't find it.

**Comment by wassie** [comment]
this is the url when it shows the error: actions/settings-game.php

**Comment by MichaelHillcox** [comment]
If that doesn't work then it's more likely that the issues is on your side due to the app either being set up wrong of if the directory that is trying to be written to does not have the correct permissions.

**Comment by wassie** [comment]
well, I just did a clean install and there wasn't a .bin directory. So I created it and also created the logfile. But I think it would be good if it was already there.

**Comment by MichaelHillcox** [comment]
I think this is now fixed. Can you confirm?

**Comment by wassie** [comment]
is also waiting for issue #16 for continuing testing.

**Comment by MichaelHillcox** [comment]
@wassie #16 has been fixed

**Comment by wassie** [comment]
ok, I will download and re-install again and let you know

**Comment by MichaelHillcox** [comment]
The installer has been completely redesigned. Tell me what you think :)

**Comment by wassie** [comment]
still got the fatal error after a complete clean install, so can't continue and test:

![afbeelding](https://cloud.githubusercontent.com/assets/17354054/26523475/b62d6ff4-4318-11e7-995a-8de2ab4213ab.png)

**Comment by MichaelHillcox** [comment]
Hmm? That would mean your config.php file exists in the app folder. Just delete it and run the install.

**Comment by wassie** [comment]
if I use the 'Go back' url, something goes wrong with redirect:
http://www.MYDOMAINNAME.com/home/wass01/domains/MYDOMAINNAME.com/public_html/echelonnew/login.php

**Comment by MichaelHillcox** [comment]
The Fatal Error page is on the bleeding edge side of new. I've not run my normal tests on the current master branch. Small issues like that might still exist.

**Comment by wassie** [comment]
even when I delete the config.php file in the app folder, I get the same error (after clearing the database). It does make a new config.php file in app dir, tho

**Comment by MichaelHillcox** [comment]
That error should only ever show if you've already installed Echelon and you've navigated yourself into the /install directory.

**Comment by MichaelHillcox** [comment]
Something is also pretty clearly out of date because that error doesn't look like that ![](https://i.imgur.com/8dPar6q.png)

**Comment by wassie** [comment]
Okay, let me tell the test scenario:
- I cleared the database
- I cleared the echelon directory
- I imported the sql file
- I downloaded the latest files from Git and uploaded all files into the echelon directory
- I run the installer
- I fill in all credentials, like email address, password and database credentials
- after the confirmation, I get the error, but the ech_config table has saved the admin credential
- after that I deleted the install directory and opened the echelon url, I get a 404 page

**Comment by MichaelHillcox** [comment]
5f4b617604135005debcc58e5b5c617f2c5b3087 as of that commit everything should now be working again. I recreated your exact install steps and found myself hitting errors too. They should now be fixed. Please tell me if you have any more issues 👍

**Comment by MichaelHillcox** [comment]
eb9b527 Correction. This commit has fully fixed all the issues you've mentioned.

**Comment by wassie** [comment]
ok, the error is gone and the installation did go well. After deleting the install dir and trying to login with my credentials, it wouldn't accept my username and password, saying it was wrong. After the second time,  I used the password forget option. The email was send, I clicked the url (http://www.MYDOMAIN.comlogin.php/?t=reset&key=d338e9f137f07e7b63c164204333fb42a9ad8b40&email=MY@EMAIL.COM) and get an error 'Server isn't found'.

By the way, I didn't got the first admin email, but I did got the password forget email. So that means that the server does send emails, but not the first admin email, right?

**Comment by MichaelHillcox** [comment]
You no longer get the first email because the first email was to simply send you your user and pass but now I allow you to set that yourself you no longer need that first email. 

The other issue I have no clue about. It's most likely this part http://www.MYDOMAIN.com( 
this part is missing a `/`    )login.php/?t=reset&key=d338e9f137f07e7b63c164204333fb42a9ad8b40&email=MY@EMAIL.COM

Can you send me the line in the config.php that says `define("PATH"` so I can confirm that it's not that of which is where the error lies.

Can you also try this url and replace the details with your stuff 
`http://www.MYDOMAIN.com/login.php/?t=reset&key=d338e9f137f07e7b63c164204333fb42a9ad8b40&email=MY@EMAIL.COM`

**Comment by wassie** [comment]
define("PATH", "/echelonnew/");

I also tried the url, with replacement of my own stuff, but still doesn't work. If I add 'echelonnew' after the .com/ it does work and after adding a new password, I can login!

**Comment by MichaelHillcox** [comment]
Okay, Can you make a new issue as this one has somewhat turned into something completely new? I will also look into this for you.

**Comment by MichaelHillcox** [comment]
@wassie Should all be fixed with that commit. Looks like the $path was being supplied incorrectly from the last developer.

**Comment by wassie** [comment]
I confirm all above is fixed!
